### ISSUE TITLE
Atom/VSCode build scripts that use system Electron?

### ISSUE THREAD

**Issue by yzgyyang** [prash-wghats/Electron-VSCode-Atom-For-FreeBSD#10]
My WIP Electron port () now installs Electron to /usr/local/lib/electron/* and create symlink to /usr/local/bin/electron (executable). Starting from here, can applications based on Electron (Atom, VSCode, ...) directly or indirectly use this?

**Comment by prash-wghats** [comment]
@yzgyyang. It should be possible. Although most of the Electron Apps comes with its own copy of electron. Main issue here is that the Apps should be compatible with the installed electron version.
For example the latest [Atom](https://github.com/atom/atom/blob/master/package.json) is using electron version 1.7. Though it doesn't mean that it will not work with electron 1.8. Should check with a Electron app expert.

**Comment by yzgyyang** [comment]
https://github.com/electron/electron/pull/12426 PR merged and will be in future Electron releases!
