### ISSUE TITLE
atom/build_atom.sh tried to install LLVM again

### ISSUE THREAD

**Issue by TELunus** [prash-wghats/Electron-VSCode-Atom-For-FreeBSD#12]
I already have LLVM installed on my system from the ports collection, but running the build_atom.sh script tried to build LLVM again.
I've uploaded the log here:
[llvm_issue.txt](https://github.com/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/files/1820663/llvm_issue.txt)

**Comment by prash-wghats** [comment]
From your log file it looks like that `chromium_make.diff` patch was reversed. Delete the `chromium\` directory before executing  `build_atom.sh`.

**Comment by TELunus** [comment]
Hmm, I'm noticing something weird here on my system.  `clang -v` says I have version 4.0 of clang and LLVM, but `pkg info llvm50` says I have verion 5.0 installed, and `pkg info llvm40` says I don't have that port installed.  This may be more a problem with my system than with the build script.  I'll keep investigating.
