### ISSUE TITLE
Add directions.

### ISSUE THREAD

**Issue by hbowden** [prash-wghats/Electron-VSCode-Atom-For-FreeBSD#21]
Can you add directions to the repo so people know what to do?

**Comment by prash-wghats** [comment]
To build each component? Or on the main page

**Comment by claywd** [comment]
I think he means on the main page but he doesn't realize you have a release page and individual folders with a readme that explains what to do

**Comment by vborovikov** [comment]
Yes, links to READMEs on the main page would be useful.

**Comment by hbowden** [comment]
Sorry for the late response. I didn't realize that you needed to `portsnap fetch` and `portsnap extract` before the build scripts would work. So maybe add that step to the readmes?
