### ISSUE TITLE
Compatibility with other versions of FreeBSD (10, 12, ...)

### ISSUE THREAD

**Issue by yzgyyang** [prash-wghats/Electron-VSCode-Atom-For-FreeBSD#8]
Hi @prash-wghats ,

I understand that different versions like FreeBSD 11.0 and 11.1 needs different patches for electron to work. But other than that, since the patch pins "freebsd11" in the code, is there a better way to pin the version like "freebsd*" instead?

Thanks!

**Comment by prash-wghats** [comment]
I think the comparison in `if` statements can use `if sys.platform.startswith('freebsd'): ` instead of `if sys.platform == 'freebsd11':`. For others specify the versions. ?.

**Comment by yzgyyang** [comment]
So basically, only need to add `'freebsd12': 'freebsd',` alongside with `'freebsd11': 'freebsd',` in https://github.com/yzgyyang/freebsd-ports-electron/search?utf8=%E2%9C%93&q=freebsd11&type=, correct?

**Comment by prash-wghats** [comment]
Yes. And see whether it works :)
